name: Deploy website to prod

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'prod'
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY_MINI_SERVER }}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
        shell: bash
      - name: Run remote command
        run: |
          ssh -o StrictHostKeyChecking=no mharry@dev.scantry.com -i ~/.ssh/private.key "ls -las"
        shell: bash
      # - name: Copy files via SCP
      #   run: scp -v mh.html mharry@dev.scantry.com:/usr/local/var/www
