name: Deploy website to prod

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'prod'
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: check env var
        env:
          OTHER_VAR: "this is the other one"
          ID_RSA: ${{ secrets.ID_RSA }}
          ID_RSA_PUB: ${{ secrets.PROD_ID_RSA_PUB }}
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          nslookup dev.scantry.com
          env
          echo "After"
          mkdir -p ~/.ssh
          ls -las ~/.ssh
          echo "$OTHER_VAR" > ~/.ssh/test_file
          echo "$TEST_SECRET" > ~/.ssh/test_secret
          echo "$ID_RSA" > ~/.ssh/id_rsa
          echo "$ID_RSA_PUB" > ~/.ssh/id_rsa.pub
          # # echo "$GH_TOKEN" > ~/.ssh/token
          ls -las ~/.ssh
          cat >>~/.ssh/config <<END
          Host prod
            HostName dev.scantry.com
            User mharry
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
          cat ~/.ssh/test_file
          cat ~/.ssh/test_secret
          cat ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa.pub
          # # cat ~/.ssh/token
      - name: Copy files via SCP
        run: scp -v mh.html mharry@dev.scantry.com:/usr/local/var/www
