name: Deploy website to prod

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: check env var
        run: |
          mkdir ~/.ssh
          ls -las ~/.ssh
          echo ${{secrets.PROD_ID_RSA_PUB}} >> ~/.ssh/id_rsa.pub
          ls -las ~/.ssh
          cat ~/.ssh/id_rsa.pub
      - name: Copy files via SCP
        run: scp mh.html mharry@www.scantry.com:/usr/local/var/www
